name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Lint-Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: General preparations
        # create empty source/backend/resources/bpmn folder necessary for running certain functionalities
        run: |
          cd source/backend
          mkdir -p resources/bpmn
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Backend unit tests
        run: |
          cd source/backend
          export PYTHONPATH=. pytest
          pytest -v

      - name: Pylint
        run: |
          pip install pylint
          pylint --rcfile ./.pylintrc ./source/backend

      - name: Build and run docker
        run: |
          cd source
          docker compose build
          docker compose up -d
          sleep 25s

      - name: API tests
        run: |
          cd api-tests
          pip install -r requirements.txt
          pytest

      - name: Stop docker
        run: |
          cd source
          docker compose stop
